### ISSUE TITLE
Various dependencies are missing

### ISSUE THREAD

**Issue by 144102** [jobam/BillMe#1]
- Common.Logging
- itextsharp
- Pechkin
- libeay32.dll
- libgcc_s_dw2-1.dll
- mingwm10.dll
- ssleay32.dll
- wkhtmltox0.dll

**Comment by 144102** [comment]
the nuget packages can be uninstalled/upgraded/installed.
The .dll are simply missing

**Comment by jobam** [comment]
Issue fixed. I just enabled automatic NuGet Packages Download. Thanks for the report.
